# GitHub Actions Workflow für Python-Anwendungen
# Dieser Workflow installiert Python-Abhängigkeiten, führt Tests mit pytest aus und lintet den Code mit flake8.

name: Python application

on: # Definiert, wann der Workflow ausgeführt werden soll
  push:
    branches: [ "main" ] # Bei jedem Push auf den main-Branch
  pull_request:
    branches: [ "main" ] # Bei jedem Pull Request, der auf den main-Branch abzielt

jobs:
  build:
    runs-on: ubuntu-latest # Der Job wird auf einem Ubuntu-Runner ausgeführt

    steps:
    - uses: actions/checkout@v4 # Checkt den Repository-Code aus
    - name: Set up Python 3.x # Konfiguriert Python auf dem Runner
      uses: actions/setup-python@v4
      with:
        python-version: "3.x" # Verwendet die neueste Python 3.x-Version

    - name: Install dependencies # Installiert alle erforderlichen Python-Abhängigkeiten
      run: |
        python -m pip install --upgrade pip # Aktualisiert pip
        pip install flake8 pytest # Installiert flake8 für Linting und pytest für Tests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # Installiert weitere Abhängigkeiten, falls requirements.txt existiert

    - name: Lint with flake8 # Führt den Linter flake8 aus, um die Codequalität zu überprüfen
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-code 0 means no issues found
        # Exit-code 1 means issues found
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
        flake8 . --count --max-complexity=10 --max-line-length=120 --statistics

    - name: Test with pytest # Führt die Unit-Tests mit pytest aus
      run: |
        pytest # Startet pytest
